const fs = require('fs');
const path = require('path');
const { assemble } = require('ass-js');

function transform(filePath) {
    if (!fs.existsSync(filePath)) return console.error("File not found:", filePath);
    
    const content = fs.readFileSync(filePath, 'utf8');
    const fileName = path.basename(filePath, '.aasm');
    const className = fileName.replace(/[^a-zA-Z0-9]/g, '');

    // 1. Extract AOB Pattern & Mask
    const aobMatch = content.match(/aobscanmodule\(([^,]+),\s*[^,]+,\s*([0-9A-Fa-f\s\?]+)\)/);
    if (!aobMatch) return console.error("Could not find aobscanmodule.");
    
    const symbol = aobMatch[1];
    const rawPattern = aobMatch[2].trim();
    const hexPattern = rawPattern.split(/\s+/).map(p => (p === '??' || p === '*') ? '\\x00' : '\\x' + p).join('');
    const mask = rawPattern.split(/\s+/).map(p => (p === '??' || p === '*') ? '?' : 'x').join('');

    // 2. Extract Hook Offset (e.g., symbol+08)
    const hookOffsetMatch = content.match(new RegExp(`${symbol}\\+([0-9A-Fa-f]+):`));
    const offsetHex = hookOffsetMatch ? `0x${hookOffsetMatch[1]}` : "0";

    // 3. Extract Disable Bytes (to handle NOPs and jump-back distance)
    const disableSection = content.split('[DISABLE]')[1] || "";
    const originalBytesMatch = disableSection.match(/db\s+([0-9A-Fa-f\s]+)/);
    const originalByteCount = originalBytesMatch ? originalBytesMatch[1].trim().split(/\s+/).length : 5;
    const nopCount = Math.max(0, originalByteCount - 5);

    // 4. AUTOMATIC ASSEMBLY
    const newMemBlock = content.split('newmem:')[1]?.split(/[a-zA-Z0-9_]+\+?[0-9]*:/)[0];
    if (!newMemBlock) return console.error("Could not find newmem block.");

    // Clean instructions for ass-js
    // It needs standard Intel syntax, so we strip CE specific labels/meta
    const lines = newMemBlock
        .split('\n')
        .map(l => l.split('//')[0].trim()) // Remove comments
        .filter(l => l && !l.endsWith(':') && !l.startsWith('label(') && !l.startsWith('registersymbol') && !l.startsWith('readMem'))
        .map(l => l.replace(/jmp return/g, 'nop\nnop\nnop\nnop\nnop')); // Placeholder for 5-byte relative jump

    let shellcodeHex = "";
    try {
        const assemblyInput = lines.join('\n');
        // ass-js assemble returns a Uint8Array
        const bytes = assemble(assemblyInput, { width: 64 }); 
        shellcodeHex = Array.from(bytes)
            .map(b => '0x' + b.toString(16).padStart(2, '0').toUpperCase())
            .join(', ');
        
        console.log(`Assembled ${lines.length} lines into ${bytes.length} bytes.`);
    } catch (e) {
        return console.error("Assembly Error! Check your AASM syntax. Error:", e.message);
    }

    // 5. Generate C++ Template
    const cppTemplate = `
#include "pch.h"
#include <shroudtopia.h>
#include <memory_utils.h>

ModMetaData metaData = {
    "${fileName}",
    "Auto-generated from ${fileName}.aasm",
    "1.0",
    "s0T7x",
    "0.0.1",
    true,
    true,
};

class ${className} : public Mod
{
    Mem::Detour* mod = nullptr;
public:
    void Load(ModContext* modContext)
    {
        const char* pattern = "${hexPattern}";
        const char* mask = "${mask}";

        uintptr_t baseAddress = (uintptr_t)GetModuleHandle(NULL);
        uintptr_t address = Mem::FindPattern(pattern, mask, baseAddress, 0x10000000);

        if (address)
        {
            address += ${offsetHex};

            // Shellcode generated by ass-js
            uint8_t modCode[] = { 
                ${shellcodeHex} 
            };

            // Calculate NOPs: Original code was ${originalByteCount} bytes, Jump is 5.
            mod = new Mem::Detour(address, modCode, sizeof(modCode), false, ${nopCount});
            
            // Calculate jump back to (Original Address + Original Byte Length)
            // We patch the last 5 bytes (the NOPs) of our shellcode with the calculated JMP
            uint32_t jumpBackOffset = (uint32_t)((address + ${originalByteCount}) - ((uintptr_t)mod->shellcode->data->address + sizeof(modCode)));
            mod->shellcode->updateValue<uint32_t>(sizeof(modCode) - 4, jumpBackOffset);
            
            modContext->Log("[${className}] Pattern found and hooked.");
        }
        else
        {
            modContext->Log("[${className}] FAILED to find pattern.");
        }
    }

    void Unload(ModContext* modContext) { if (mod) delete mod; }
    void Activate(ModContext* modContext) { if (mod) active = mod->activate(); }
    void Deactivate(ModContext* modContext) { if (mod) { mod->deactivate(); active = false; } }
    ModMetaData GetMetaData() { return metaData; }
};

extern "C" __declspec(dllexport) Mod* CreateModInstance() {
    return new ${className}();
}
`;

    fs.writeFileSync(path.join(path.dirname(filePath), `${className}.cpp`), cppTemplate);
    console.log(`Successfully generated: ${className}.cpp`);
}

// Execution
const target = process.argv[2];
if (!target) {
    console.log("Usage: node aasm-to-cpp.js yourfile.aasm");
} else {
    transform(target);
}