[package]
name = "shroudtopia-assets"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
kfc = { path = "../../../../third-party/kfc-parser/crates/kfc", features = ["resource"] }
serde_json.workspace = true
uuid.workspace = true
